apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app1 
  labels: 
    # replica set labels
    purpose: ingress
    project: roboshop
    environment: dev
    app: app1
spec:
  replicas: 1
  # these are the labels replica set use to crete pod replicas, this should match pod labels 
  selector:
    matchLabels:
      purpose: ingress
      project: roboshop
      environment: dev
      app: app1

  # this pod defination    
  template:
    metadata:
      labels:
        purpose: ingress
        project: roboshop
        environment: dev
        app: app1       
    spec:
      containers:
      - name: app1
        #image: nginx:stable-perl
        image: nareshkumart/app1:v1

---
apiVersion: v1
kind: Service
metadata:
  name: app1  # service name
  labels:
    purpose: ingress
spec:
  selector:
    purpose: ingress
    project: roboshop
    env: dev
    app: app1
  ports: 
  - name: http
    protocol:  TCP
    port: 80 # service port
    targetPort: 80 # container port

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:090074823871:certificate/97e32bb3-29f0-4442-8144-fa053475355c
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    #alb.ingress.kubernetes.io/group.name: joindevops
spec:
  ingessClassName: app1
  rules:
  - host: "app1.daws84s.space"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app1
            port:
              number: 80

