apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app2 
  labels: 
    # replica set labels
    purpose: ingress
    project: roboshop
    app: app2
spec:
  replicas: 2
  # these are the labels replica set use to crete pod replicas, this should match pod labels 
  selector:
    matchLabels:
      purpose: ingress
      project: roboshop
      app: app2

  # this pod defination    
  template:
    metadata:
      labels:
        purpose: ingress
        project: roboshop
        app: app2       
    spec:
      containers:
      - name: app2
        #image: nginx:stable-perl
        image: nareshkumart/app2:v1

--- 
apiVersion: v1
kind: Service
metadata: 
  name: app2
  labels:
    purpose: ingress
    project: roboshop
    app: app2
spec:
  selector: 
    purpose: ingress
    project: roboshop
    app: app2
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:090074823871:certificate/c0660436-8910-4743-bb92-5342b0b1c593
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: joindevops
spec:
  ingressClassName: alb
  rules:
  - host: "app2.daws84s.space"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app2
            port:
              number: 80 # app1 service port